//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp_Net_Entity_FrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Times
    {
        public int Id { get; set; }
        public string Nome_Time { get; set; }
        public int Titulos { get; set; }
    }
}
